<?php

namespace App\Models\Template;

use Illuminate\Database\Eloquent\Model;

class PrescriptionTemplate extends Model
{
    protected $fillable = ['name', 'description'];

    protected $appends = [
        'encrypted_id'
    ];

    public function getEncryptedIdAttribute()
    {
        return encrypt($this->id);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($modal) {
            $modal->doctor_id = auth()->user()->doctor->id;
        });
    }

    public function drugs()
    {
        return $this->hasMany(PrescriptionTemplateDrug::class);
    }

    public function inspection()
    {
        return $this->hasOne(PrescriptionTemplateInspection::class);
    }
}
