<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Admin extends Model
{
    protected $fillable = [
        'title', 'full_name', 'email', 'phone', 'address'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($modal) {
            $modal->created_by = auth()->check() ? auth()->user()->id : 1;
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}
