<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class AppointmentFollowUpNote extends Model
{
    protected $fillable = [
        'note', 'appointment_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($modal) {
            $modal->appointment_id = decrypt($modal->appointment_id);
            $modal->created_by = auth()->user()->id;
        });
    }

    public function appointment()
    {
        return $this->belongsTo(Appointment::class);
    }

    public function createdBy()
    {
        return $this->belongsTo(User::class,'created_by');
    }
}
