<?php

namespace App\Models;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Department extends Model
{
    use SoftDeletes;
    use Sluggable;

    protected $dates = [
        'deleted_at'
    ];

    protected $fillable = [
        'title', 'note'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->created_by = auth()->check() ? auth()->user()->id : 0;
        });
    }

    public function doctors()
    {
        return $this->hasMany(Doctor::class);
    }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
}
