<?php

namespace App\Models;

use App\User;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{

    use Sluggable;

    protected $fillable = [
        'title', 'full_name', 'phone', 'photo', 'sex', 'info', 'descriptions', 'department_id','location','services','nmc_number','normal_consultation_fee','video_consultation_fee','doctor_status','experience','qualification'
    ];

    protected $appends = [
        'encrypted_id'
    ];

    public function getEncryptedIdAttribute()
    {
        return encrypt($this->id);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->created_by = auth()->check() ? auth()->user()->id : 0;
        });
    }

    public function department()
    {
        return $this->belongsTo(Department::class)->withTrashed();
    }

    public function availableToday()
    {
        return "123";
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function schedules()
    {
        return $this->hasMany(Schedule::class);
    }

    public function appointmentSchedules()
    {
        return $this->hasMany(Schedule::class)->with('appointmentDetails');
    }

    public function prescriptionSetting()
    {
        return $this->hasOne(PrescriptionSetting::class, 'doctor_id');
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'full_name'
            ]
        ];
    }
}
