<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Drug extends Model
{

    protected $fillable = [
        'trade_name','generic_name','note','department_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $model->created_by = auth()->check() ? auth()->user()->id : 0;
        });
    }

    public function department()
    {
        return $this->belongsTo(Department::class);
    }


}
