<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PatientMedicalNote extends Model
{
    protected $fillable = ['note', 'appointment_id', 'patient_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($modal) {
            $modal->created_by = auth()->user()->id;
        });
    }

    public function appointment()
    {
        return $this->belongsTo(Appointment::class);
    }
}
