<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PatientMedicalDocument extends Model
{
    protected $fillable = ['title','note','appointment_id','patient_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($model){
           $model->created_by = auth()->user()->id;
           $model->appointment_id = decrypt($model->appointment_id);
           $model->patient_id = decrypt($model->patient_id);
        });
    }

    public function appointment()
    {
        return $this->belongsTo(Appointment::class);
    }
}
