<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Auth;

class PatientPayment extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'patient_id', 'appointment_id', 'payment_method', 'payment_info', 'payment_amount', 'doctor_id', 'created_by'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // self::creating(function ($model) {
        //     $model->created_by = auth()->user()->id;

        // });
    }

    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }

    public function doctor()
    {
        return $this->belongsTo(Doctor::class);
    }

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function appointment()
    {
        return $this->belongsTo(Appointment::class, 'appointment_id');
    }
}
