<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PrescriptionHelper extends Model
{
    protected $fillable = [
        'helper_text', 'category'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->created_by = auth()->user()->id;
            $model->public = auth()->user()->role == 1 ? true : false;
        });
    }
}
