<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Prescription extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'appointment_id', 'patient_id', 'doctor_id'
    ];

    protected $appends = [
        'encrypted_id'
    ];

    public function getEncryptedIdAttribute()
    {
        return encrypt($this->id);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->search_id = 'RX' . str_pad($model->appointment_id . $model->patient_id . $model->doctor_id, 6, 0, STR_PAD_LEFT).Carbon::now()->format('ymdgi');
        });
    }

    public function appointment()
    {
        return $this->belongsTo(Appointment::class);
    }

    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }

    public function doctor()
    {
        return $this->belongsTo(Doctor::class);
    }

    public function drugs()
    {
        return $this->hasMany(PrescriptionDrug::class);
    }

    public function inspection()
    {
        return $this->hasOne(PrescriptionInspection::class);
    }
}
