<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{

    public function scheduleDetails()
    {
        return $this->hasMany(ScheduleDetails::class);
    }

    public function appointmentDetails()
    {
        return $this->hasMany(ScheduleDetails::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $model->created_by = auth()->check() ? auth()->user()->id : 0;
        });
    }
}
