<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ScheduleDetails extends Model
{

    protected $fillable=[
        'schedule_id','start_time','end_time'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($model){
           $model->schedule_id = decrypt($model->schedule_id);
           $model->created_by = auth()->user()->id;
        });
    }

    public function schedule()
    {
        return $this->belongsTo(Schedule::class);
    }
}
